### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by Zearin** [Zearin/eleventy-plugin-pug#5]
As I continue to update Eleventy v3 alpha to the latest version, I noticed the following test failure that _might_ indicate an edge case in Eleventy’s new `ProjectDirectories` class:

<details>
<summary>Relevant error output:</summary>

```bash
✖ failing tests:

test at test/test-plugin-data-access.js:50:3
✖ The compilation can use the data  (154.076271ms)
  Error: The "_src" `input` parameter (directory or file path) must exist on the file system (unless detected as a glob by the `is-glob` package)
      at #setInputRaw (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:147:12)
      at ProjectDirectories.setViaConfigObject (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:61:21)
      at TemplateConfig.mergeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:410:22)
      at async TemplateConfig.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:186:17)
      at async Eleventy.initializeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:162:3)
      at async Eleventy.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:416:4)
      at async Eleventy.executeBuild (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:1216:4)
      at async TestContext.<anonymous> (file:///Users/amrogers/Projects/eleventy-plugin-pug/test/test-plugin-data-access.js:51:4)
      at async Test.run (node:internal/test_runner/test:748:9)
      at async Promise.all (index 0)

test at test/test-plugin-data-functions.js:50:3
✖ The compilation can use the data function  (156.265139ms)
  Error: The "_src" `input` parameter (directory or file path) must exist on the file system (unless detected as a glob by the `is-glob` package)
      at #setInputRaw (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:147:12)
      at ProjectDirectories.setViaConfigObject (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:61:21)
      at TemplateConfig.mergeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:410:22)
      at async TemplateConfig.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:186:17)
      at async Eleventy.initializeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:162:3)
      at async Eleventy.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:416:4)
      at async Eleventy.executeBuild (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:1216:4)
      at async TestContext.<anonymous> (file:///Users/amrogers/Projects/eleventy-plugin-pug/test/test-plugin-data-functions.js:51:4)
      at async Test.run (node:internal/test_runner/test:748:9)
      at async Promise.all (index 0)

test at test/test-plugin-minimal-setup.js:74:4
✖ Can build a Pug file (44.218444ms)
  Error: The "_src" `input` parameter (directory or file path) must exist on the file system (unless detected as a glob by the `is-glob` package)
      at #setInputRaw (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:147:12)
      at ProjectDirectories.setViaConfigObject (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Util/ProjectDirectories.js:61:21)
      at TemplateConfig.mergeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:410:22)
      at async TemplateConfig.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/TemplateConfig.js:186:17)
      at async Eleventy.initializeConfig (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:162:3)
      at async Eleventy.init (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:416:4)
      at async Eleventy.executeBuild (file:///Users/amrogers/Projects/eleventy-plugin-pug/node_modules/@11ty/eleventy/src/Eleventy.js:1216:4)
      at async TestContext.<anonymous> (file:///Users/amrogers/Projects/eleventy-plugin-pug/test/test-plugin-minimal-setup.js:75:5)
      at async Test.run (node:internal/test_runner/test:748:9)
      at async Promise.all (index 0)
```

The error claims that the folder doesn’t exist, but it does… 🤔

**Comment by zachleat** [comment]
I think the misunderstanding here is that when you return `dir` from your configuration file callback, those values are not relative to the configuration file. They are relative to the command directory. So with that knowledge, `_src` does not exist! I think your params to the Eleventy constructor are absolute though, so maybe just remove those return objects in your config file?

**Comment by Zearin** [comment]
I have been editing existing {code,prose} so long that I am finding it difficult to write from scratch!

Thank you for the help thank 🙏 I will try and fix it tonight or tomorrow.
